
name: Veracode SCA

on: 
  #schedule:
  #  - cron: 15 14 * * 6
  push:
  workflow_dispatch:
    
    
jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: lerer/veracode-sca@v1.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true 
          path: "app"
          debug: true
